server:
  port: 8080
spring:
  application:
    name: development
  datasource:
    schema: public
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/admin
    username: admin
    password: xPFe5CxBDtsqTYg
  liquibase:
    url: jdbc:postgresql://localhost:5432/admin
    user: admin
    password: xPFe5CxBDtsqTYg
    change-log: db/changelog/changelog-master.xml
  webflux:
    base-path: /api
springdoc:
  swagger-ui:
    path: /doc
