spring:
  datasource.schema: public # схема БД по умолчанию
  r2dbc:
    url: r2dbc:proxy:postgresql://fsociety-org.ru:5432/admin?proxyListener=ru.admin.config.SqlLogger
  liquibase:
    url: jdbc:postgresql://fsociety-org.ru:5432/admin
  rabbitmq:
    host: fsociety-org.ru
management:
  endpoint.health.show-details: always
  endpoints.web.exposure.include: auditevents,beans,caches,conditions,configprops,env,flyway,health,heapdump,httptrace,info,logfile,loggers,metrics,mappings,shutdown,threaddump
logging.level:
  org.springframework:
    amqp: DEBUG
    messaging: DEBUG
  web: DEBUG
  ru.admin.config: DEBUG
springdoc:
  swagger-ui.path: /doc
  api-docs:
    enabled: true
  show-actuator: false
blocking-call-detection.enable: true
account-activation:
  link: https://fsociety-org.ru/api/user/confirm
