server:
  port: 8443
  ssl:
    key-store: classpath:ssl/certificate.p12
    key-store-password: 31165119221
    key-store-type: PKCS12
spring:
  datasource.schema: public
  r2dbc:
    url: r2dbc:proxy:postgresql://postgres:5432/admin?proxyListener=ru.admin.config.SqlLogger
  liquibase:
    url: jdbc:postgresql://postgres:5432/admin
  rabbitmq:
    host: rabbitmq
management:
  endpoints.web.exposure.include: beans,caches,configprops,env,health,httptrace,info,logfile,loggers,mappings,threaddump
blocking-call-detection.enable: false
springdoc:
  swagger-ui.path: /doc
  api-docs:
    enabled: true
account-activation:
  link: https://fsociety-org.ru/api/users/confirm
