version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=xPFe5CxBDtsqTYg
      - POSTGRES_DB=admin
    volumes:
      - ./docker-volume/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=in.the.middle.of.the.chaos@gmail.com
      - RABBITMQ_DEFAULT_PASS=Nine!=362880
    volumes:
      - ./docker-volume/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  app:
    image: casket/admin
    container_name: app
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8443:8443
    depends_on:
      - postgres
      - rabbitmq
