# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Обновить docker image приложения, а затем запустить его на сервере

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Установить JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Создать docker image, используя maven
      run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=casket/admin -Dmaven.test.skip=true
    - name: Авторизация в DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Запушить образ в DockerHub
      run: docker push casket/admin:latest
    - name: Обновить приложение на сервере
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: ${{ secrets.HOST_PORT }}
        script: docker-compose pull && docker-compose up -d && docker image prune -a --filter "until=7200h"
